version: "3"

services:
  mongodb:
    container_name: livraria-api-mongo
    image: mongo:latest
    volumes:
      - /docker-config/database:/data/db
    ports:
      - "27017:27017"

  livraria-api:
    depends_on:
      - mongodb
    container_name: livraria-api-node
    build:
      context: ./
    image: livraria-api:1.0
    volumes:
      - "./:/var/www/app"
    links:
      - "mongodb:mongodb"
    ports:
      - "6590:6590"
